# tests/specs/frames.py
"""The executable abstract specification (docs/cpm-test-spec.md §4).

Pure data, deliberately boring: one Frame per row of the frame
catalogue, every expectation declarative (no lambdas, no pytest, no
package imports). The concrete interpreters are the tier-routed
consumers tests/test_frames_{model,usecase,cli}.py; shared builders
live in tests/specs/builders.py. Adding a behaviour starts here.

Row conventions
- tier 1 rows carry model_call/model_input (a model constructor + raw
  input) and report/exception expectations.
- tier 2 rows carry usecase (+files/cloud seed) and ActionList /
  gateway-state expectations.
- tier 3 rows carry argv/env and rc/stdout/stderr expectations; the
  consumer inserts --project unless raw_argv is set. No command prompts
  (--yes is the consent), so no row carries stdin answers.
- expect_* None means "not checked"; () means "checked empty".
- cloud seeds and expect_cloud tuples are interpreted by
  builders.seed_gateway / builders.check_cloud.
- Frames that cannot be expressed deterministically in this format are
  listed in DEFERRED with a reason; tier 4 stays hand-written (TIER4).
"""
from dataclasses import dataclass


@dataclass(frozen=True)
class Frame:
    id: str                    # "FRAME-<ASPECT>-<nn>[.literal]" — unique
    tier: int                  # 1 model · 2 loader/usecase/adapter · 3 cli
    aspect: str                # A-number from docs/cpm-test-spec.md §2
    summary: str               # one line, human-reviewable
    files: dict = None         # relpath -> yaml text (bytes allowed)
    cloud: dict = None         # FakeGateway seed spec (builders.seed_gateway)
    model_call: str = None     # tier 1 constructor / tier 3 "load_config"
    model_input: object = None # tier 1 raw input; tier 2 op script / name
    usecase: str = None        # tier 2 operation under test
    argv: list = None          # tier 3, without --project (consumer adds it)
    env: dict = None           # env overrides (None value deletes the var)
    raw_argv: bool = False     # tier 3: use argv verbatim (no --project)
    chdir: bool = False        # tier 3: run from inside the project dir
    inject_gateway: bool = True  # False: exercise the credentials gate
    expect_rc: int = None
    expect_out: tuple = ()     # substrings of stdout
    expect_out_absent: tuple = ()   # substrings that must NOT be printed
    expect_err: tuple = ()     # substrings of stderr
    expect_error_contains: tuple = ()  # report errors / raised message
    expect_ok: bool = None     # report.ok / no exception
    expect_value: object = None    # canonical result (per model_call)
    expect_actions: tuple = None   # [(sign, type, group[, detail-sub]), ...]
    expect_unmanaged: tuple = None
    expect_clears: tuple = None
    expect_overlaps: tuple = None
    expect_nics: tuple = None      # ((ip, port_id), ...)
    expect_results: tuple = None   # execution statuses, exact order
    expect_phases: tuple = None    # per-budget-phase status tuples (resume)
    expect_audit: tuple = None     # created group names in the audit record
    expect_call_log: list = None   # exact FakeGateway write log
    expect_cloud: tuple = ()       # declarative post-run cloud assertions
    expect_files: tuple = ()       # relpaths that must exist afterwards
    expect_json: dict = None       # parsed --json output: subset compare
    expect_warn: tuple = ()        # report warning substrings


# ---- yaml text builders (keep tier-2/3 rows one-liners) ----

def _group(name="web", desc=None, members=("10.0.1.10",)):
    lines = [f"name: {name}"]
    if desc is not None:
        lines.append(f"description: {desc}")
    if members is None:            # key absent
        pass
    elif not members:
        lines.append("members: []")
    else:
        lines.append("members:")
        lines.extend(f"  - ip: {ip}" for ip in members)
    return "\n".join(lines) + "\n"


def _rules(sg="web", ingress=(), egress=(), null=(), empty=()):
    """Rules file text. Per direction: `null` renders "key: null" (the
    remove-all guidance error), `empty` renders "key: []" (managed
    remove-all), a non-empty tuple renders the rows, otherwise the key
    is absent (unmanaged). Rows are (remote, protocol, ports-yaml)
    triples; ports None = key absent."""
    lines = [f"security_group: {sg}"]
    for key, rows in (("ingress", ingress), ("egress", egress)):
        rk = "source" if key == "ingress" else "destination"
        if key in null:
            lines.append(f"{key}: null")
            continue
        if key in empty:
            lines.append(f"{key}: []")
            continue
        if not rows:
            continue
        lines.append(f"{key}:")
        for remote, protocol, ports in rows:
            parts = [f"{rk}: {remote}", f"protocol: {protocol}"]
            if ports is not None:
                parts.append(f"ports: {ports}")
            lines.append("  - {" + ", ".join(parts) + "}")
    return "\n".join(lines) + "\n"


def _cli(**kw) -> dict:
    """Tier-3 shorthand: the standard one-group project + one NIC."""
    kw.setdefault("files", {"groups/web.yaml": _group()})
    kw.setdefault("cloud", {"nics": [{"port_id": "p1", "ip": "10.0.1.10"}]})
    return kw


FRAMES: list = [
    # ================= T1 backlog: A1 group-name validity =================
    Frame("NAME-01.a", 1, "A1", "single-char name is valid",
          model_call="parse_group", model_input={"name": "a", "members": []},
          expect_ok=True, expect_value=("a", "", ())),
    Frame("NAME-01.b", 1, "A1", "digit-leading name is valid",
          model_call="parse_group", model_input={"name": "1web", "members": []},
          expect_ok=True, expect_value=("1web", "", ())),
    Frame("NAME-01.c", 1, "A1", "64-char name is the length boundary",
          model_call="parse_group", model_input={"name": "a" * 64, "members": []},
          expect_ok=True, expect_value=("a" * 64, "", ())),
    Frame("NAME-01.d", 1, "A1", "trailing-hyphen name is valid",
          model_call="parse_group", model_input={"name": "web-", "members": []},
          expect_ok=True, expect_value=("web-", "", ())),
    Frame("NAME-02", 1, "A1", "uppercase name is rejected with the regex",
          model_call="parse_group", model_input={"name": "Web", "members": []},
          expect_ok=False, expect_error_contains=("must match",)),
    Frame("NAME-02.a", 1, "A1", "underscore name is rejected",
          model_call="parse_group", model_input={"name": "web_tier", "members": []},
          expect_ok=False, expect_error_contains=("must match",)),
    Frame("NAME-02.b", 1, "A1", "leading-hyphen name is rejected",
          model_call="parse_group", model_input={"name": "-web", "members": []},
          expect_ok=False, expect_error_contains=("must match",)),
    Frame("NAME-02.c", 1, "A1", "65-char name is too long",
          model_call="parse_group", model_input={"name": "a" * 65, "members": []},
          expect_ok=False, expect_error_contains=("must match",)),
    Frame("NAME-04", 1, "A1", "absent name is a type error, not a regex miss",
          model_call="parse_group", model_input={"members": []},
          expect_ok=False, expect_error_contains=("name must be a string",)),
    Frame("NAME-04.a", 1, "A1", "non-string name (int) is a type error",
          model_call="parse_group", model_input={"name": 123, "members": []},
          expect_ok=False, expect_error_contains=("name must be a string, got 123",)),

    # ================= T1 backlog: A5 security_group field =================
    Frame("SGF-02", 1, "A5", "absent security_group fails the charset check",
          model_call="parse_rules_file", model_input={"ingress": []},
          expect_ok=False, expect_error_contains=("security_group None must match",)),
    Frame("SGF-02.a", 1, "A5", "empty-string security_group is rejected",
          model_call="parse_rules_file", model_input={"security_group": "", "ingress": []},
          expect_ok=False, expect_error_contains=("security_group '' must match",)),
    Frame("SGF-02.b", 1, "A5", "non-string security_group is rejected",
          model_call="parse_rules_file", model_input={"security_group": 42, "ingress": []},
          expect_ok=False, expect_error_contains=("security_group 42 must match",)),
    Frame("SGF-02.c", 1, "A5", "uppercase security_group is rejected",
          model_call="parse_rules_file", model_input={"security_group": "Web", "ingress": []},
          expect_ok=False, expect_error_contains=("must match",)),

    # ================= T1 backlog: A6 direction section =================
    Frame("SECT-04.a", 1, "A6", "egress null is the remove-all guidance error",
          model_call="parse_rules_file",
          model_input={"security_group": "x", "egress": None},
          expect_ok=False,
          expect_error_contains=("egress must be a list", "remove-all")),
    Frame("SECT-05", 1, "A6", "non-list section (bare string) is rejected",
          model_call="parse_rules_file",
          model_input={"security_group": "x", "ingress": "80"},
          expect_ok=False, expect_error_contains=("ingress must be a list",)),
    Frame("SECT-06", 1, "A6", "non-mapping rule entry is rejected",
          model_call="parse_rules_file",
          model_input={"security_group": "x", "ingress": [80]},
          expect_ok=False, expect_error_contains=("rule must be a mapping",)),

    # ================= T1 backlog: A7 remote =================
    Frame("REMOTE-06", 1, "A7", "empty remote is rejected",
          model_call="parse_remote", model_input="",
          expect_ok=False, expect_error_contains=("empty remote",)),
    Frame("REMOTE-06.a", 1, "A7", "whitespace-only remote is rejected",
          model_call="parse_remote", model_input=" ",
          expect_ok=False, expect_error_contains=("empty remote",)),
    Frame("REMOTE-07", 1, "A7", "garbage with a slash is not a CIDR",
          model_call="parse_remote", model_input="tcp/80",
          expect_ok=False, expect_error_contains=("tcp/80",)),
    Frame("REMOTE-07.a", 1, "A7", "rules entry without a source is rejected",
          model_call="parse_rules_file",
          model_input={"security_group": "x", "ingress": [{}]},
          expect_ok=False, expect_error_contains=("source is required",)),
    Frame("REMOTE-07.b", 1, "A7", "non-string source is rejected",
          model_call="parse_rules_file",
          model_input={"security_group": "x",
                       "ingress": [{"source": 42, "protocol": "tcp"}]},
          expect_ok=False, expect_error_contains=("source is required",)),

    # ============ T1 backlog: A8 protocol (valid non-tcp family) ============
    Frame("PROTO-01.a", 1, "A8", "udp is a valid protocol",
          model_call="parse_rules_file",
          model_input={"security_group": "x", "ingress": [
              {"source": "10.0.0.0/8", "protocol": "udp", "ports": "53"}]},
          expect_ok=True,
          expect_value={"sg": "x", "ingress_managed": True,
                        "egress_managed": False, "ingress": 1, "egress": 0,
                        "rule0": ("ingress", "udp", "53", ("cidr", "10.0.0.0/8"))}),
    Frame("PROTO-01.b", 1, "A8", "icmpv6 is valid and portless",
          model_call="parse_rules_file",
          model_input={"security_group": "x", "ingress": [
              {"source": "0.0.0.0/0", "protocol": "icmpv6"}]},
          expect_ok=True,
          expect_value={"sg": "x", "ingress_managed": True,
                        "egress_managed": False, "ingress": 1, "egress": 0,
                        "rule0": ("ingress", "icmpv6", None, ("cidr", "0.0.0.0/0"))}),
    Frame("PROTO-01.c", 1, "A8", "all is valid and portless",
          model_call="parse_rules_file",
          model_input={"security_group": "x", "ingress": [
              {"source": "0.0.0.0/0", "protocol": "all"}]},
          expect_ok=True,
          expect_value={"sg": "x", "ingress_managed": True,
                        "egress_managed": False, "ingress": 1, "egress": 0,
                        "rule0": ("ingress", "all", None, ("cidr", "0.0.0.0/0"))}),

    # ================= T1 backlog: A9 ports junk family =================
    Frame("PORTS-06", 1, "A9", "named port is junk",
          model_call="parse_ports", model_input="http",
          expect_ok=False, expect_error_contains=("bad port",)),
    Frame("PORTS-06.a", 1, "A9", "bool is a type error, not 0/1",
          model_call="parse_ports", model_input=True,
          expect_ok=False, expect_error_contains=("got bool",)),
    Frame("PORTS-06.b", 1, "A9", "float is a type error",
          model_call="parse_ports", model_input=80.5,
          expect_ok=False, expect_error_contains=("got float",)),
    Frame("PORTS-06.c", 1, "A9", "empty entry inside the list is junk",
          model_call="parse_ports", model_input="80,,443",
          expect_ok=False, expect_error_contains=("empty entry",)),
    Frame("PORTS-06.d", 1, "A9", "negative number parses as a reversed range",
          model_call="parse_ports", model_input="-1",
          expect_ok=False, expect_error_contains=("bad port range",)),
    Frame("PORTS-06.e", 1, "A9", "unicode digit forms are junk",
          model_call="parse_ports", model_input="⁸⁰",
          expect_ok=False, expect_error_contains=("bad port",)),

    # ============ T1 backlog: A10 protocol-ports consistency ============
    Frame("PP-02", 1, "A10", "icmpv6 with ports is rejected",
          model_call="parse_rules_file",
          model_input={"security_group": "x", "ingress": [
              {"source": "a", "protocol": "icmpv6", "ports": "80"}]},
          expect_ok=False, expect_error_contains=("icmpv6 rules must not have ports",)),
    Frame("PP-03", 1, "A10", "icmp with empty-string ports is portless",
          model_call="parse_rules_file",
          model_input={"security_group": "x", "ingress": [
              {"source": "a", "protocol": "icmp", "ports": ""}]},
          expect_ok=True,
          expect_value={"sg": "x", "ingress_managed": True,
                        "egress_managed": False, "ingress": 1, "egress": 0,
                        "rule0": ("ingress", "icmp", None, ("group", "a"))}),
    Frame("PP-03.a", 1, "A10", "icmpv6 with empty-list ports is portless",
          model_call="parse_rules_file",
          model_input={"security_group": "x", "ingress": [
              {"source": "a", "protocol": "icmpv6", "ports": []}]},
          expect_ok=True,
          expect_value={"sg": "x", "ingress_managed": True,
                        "egress_managed": False, "ingress": 1, "egress": 0,
                        "rule0": ("ingress", "icmpv6", None, ("group", "a"))}),
    Frame("PP-03.b", 1, "A10", "all without a ports key is portless",
          model_call="parse_rules_file",
          model_input={"security_group": "x", "ingress": [
              {"source": "a", "protocol": "all"}]},
          expect_ok=True,
          expect_value={"sg": "x", "ingress_managed": True,
                        "egress_managed": False, "ingress": 1, "egress": 0,
                        "rule0": ("ingress", "all", None, ("group", "a"))}),

    # ============ T1 backlog: A11 rule-identity uniqueness ============
    Frame("DUPRULE-01.a", 1, "A11",
          "canonical-equivalent ports are the same identity",
          model_call="parse_rules_file",
          model_input={"security_group": "x", "ingress": [
              {"source": "d", "protocol": "tcp", "ports": "443,80"},
              {"source": "d", "protocol": "tcp", "ports": "80,443"}]},
          expect_ok=False, expect_error_contains=("duplicate",)),

    # ============== T2 backlog: A12 file-store integrity ==============
    Frame("STORE-02", 2, "A12", "empty project (no yaml) loads ok",
          usecase="load", files={"groups/.keep": ""},
          expect_ok=True, expect_value={"groups": [], "rules": []}),
    Frame("STORE-03.a", 2, "A12", "null document is a load error",
          usecase="load", files={"groups/x.yaml": "null\n"},
          expect_ok=False, expect_error_contains=("empty",)),
    Frame("STORE-03.b", 2, "A12", "list document is not a mapping",
          usecase="load", files={"groups/x.yaml": "- a\n- b\n"},
          expect_ok=False, expect_error_contains=("must be a YAML mapping",)),
    Frame("STORE-06.a", 2, "A12", ".yml sibling in rules/ warns too",
          usecase="load",
          files={"groups/web.yaml": _group(members=()),
                 "rules/extra.yml": "security_group: web\n"},
          expect_ok=True, expect_warn=("rules/extra.yml",)),
    Frame("STORE-11", 2, "A12", "several bad files accumulate errors",
          usecase="load",
          files={"groups/bad.yaml": "name: bad\n  members: [\n",
                 "groups/other.yaml": "name: Web\nmembers: []\n"},
          expect_ok=False,
          expect_error_contains=("YAML syntax error", "must match")),

    # ================ T2 backlog: A14 member resolution ================
    Frame("RES-03.a", 2, "A14",
          "vm-known multi-match lists candidates and drops overlap info",
          usecase="resolve",
          files={"groups/web.yaml": _group(name="web"),
                 "groups/mon.yaml": _group(name="mon")},
          cloud={"nics": [{"port_id": "p1", "ip": "10.0.1.10", "vm": "vm-a"},
                          {"port_id": "p2", "ip": "10.0.1.10"}]},
          expect_ok=False, expect_error_contains=("matches multiple NICs",
                                                  "vm=vm-a"),
          expect_overlaps=()),      # constraint 2: multi-match exits `nics`

    # =================== T2 backlog: A15/A16 plan ===================
    Frame("PLAN-08", 2, "A16",
          "cloud remote_group_id maps to the peer group's name",
          usecase="plan",
          files={"groups/web.yaml": _group(members=()),
                 "groups/peer.yaml": _group(name="peer", members=()),
                 "rules/web.yaml": _rules(ingress=[("peer", "tcp", '"80"')])},
          cloud={"sgs": [{"id": "sg-web", "name": "web"},
                         {"id": "sg-peer", "name": "peer"}],
                 "rules": [{"id": "r1", "sg": "sg-web", "direction": "ingress",
                            "protocol": "tcp", "ports": "80",
                            "rgid": "sg-peer"}]},
          expect_actions=(), expect_unmanaged=()),
    Frame("PLAN-14", 2, "A18",
          "attached-but-undesired member is detached, missing one attached",
          usecase="plan",
          files={"groups/web.yaml": _group()},
          cloud={"sgs": [{"id": "sg-web", "name": "web"}],
                 "nics": [{"port_id": "p1", "ip": "10.0.1.10"},
                          {"port_id": "p9", "ip": "10.0.1.99"}],
                 "attached": [["sg-web", "p9"]]},
          expect_actions=(("+", "member", "web", "ip 10.0.1.10"),
                          ("-", "member", "web", "ip 10.0.1.99")),
          expect_unmanaged=()),
    Frame("PLAN-18", 2, "A16",
          "icmp rule plans with the all-ports literal",
          usecase="plan",
          files={"groups/web.yaml": _group(members=()),
                 "rules/web.yaml": _rules(ingress=[("0.0.0.0/0", "icmp", None)])},
          expect_actions=(("+", "group", "web"),
                          ("+", "rule", "web",
                           "ingress icmp all from cidr:0.0.0.0/0")),
          expect_unmanaged=()),

    # ================== T2 backlog: A19 execution ==================
    Frame("EXEC-03", 2, "A19", "budget 0 throttles everything",
          usecase="execute", files={"groups/web.yaml": _group()},
          cloud={"nics": [{"port_id": "p1", "ip": "10.0.1.10"}], "budget": 0},
          expect_results=("throttled", "throttled"),
          expect_cloud=(("sg_missing", "web"),)),
    Frame("EXEC-05", 2, "A19",
          "mid-action failure isolates and skips dependents",
          usecase="execute",
          files={"groups/boom.yaml": _group(name="boom"),
                 "rules/boom.yaml": _rules(
                     sg="boom", ingress=[("0.0.0.0/0", "tcp", '"22"')])},
          cloud={"nics": [{"port_id": "p1", "ip": "10.0.1.10"}],
                 "raises": [{"method": "create_security_group",
                             "name": "boom", "exc": "CloudError",
                             "msg": "provision failed"}]},
          expect_results=("failed", "failed", "failed"),
          expect_cloud=(("sg_missing", "boom"),)),
    Frame("EXEC-07", 2, "A19",
          "CloudThrottled from the gateway throttles the rest "
          "(unlike CloudError it is never a hard failure)",
          usecase="execute",
          files={"groups/boom.yaml": _group(name="boom"),
                 "rules/boom.yaml": _rules(
                     sg="boom", ingress=[("0.0.0.0/0", "tcp", '"22"')])},
          cloud={"nics": [{"port_id": "p1", "ip": "10.0.1.10"}],
                 "raises": [{"method": "create_security_group",
                             "exc": "CloudThrottled", "msg": "cloud 429"}]},
          expect_results=("throttled", "throttled", "throttled"),
          expect_cloud=(("sg_missing", "boom"),)),

    # ================ T2 backlog: A24 FakeGateway fidelity ================
    Frame("FAKE-03", 2, "A24",
          "delete_security_group cascades rules and attachments only "
          "for that SG",
          usecase="fake",
          cloud={"sgs": [{"id": "sg-web", "name": "web"},
                         {"id": "sg-other", "name": "other"}],
                 "rules": [{"id": "r1", "sg": "sg-web", "direction": "egress",
                            "protocol": "tcp", "ports": "80",
                            "prefix": "0.0.0.0/0"},
                           {"id": "r2", "sg": "sg-other", "direction": "egress",
                            "protocol": "tcp", "ports": "443",
                            "prefix": "0.0.0.0/0"}],
                 "nics": [{"port_id": "p1", "ip": "10.0.1.10"}],
                 "attached": [["sg-web", "p1"], ["sg-other", "p1"]]},
          model_input=(("delete_sg", "sg-web"),),
          expect_cloud=(("sg_missing", "web"), ("sg_exists", "other"),
                        ("rule_count", "sg-other", 1),
                        ("rule_count", "sg-web", 0),
                        ("detached", "sg-web", "p1"),
                        ("attached", "sg-other", "p1"))),

    # ================ T2 backlog: A23 Huawei translation ================
    Frame("XLATE-02.c", 2, "A23",
          "wire rule with only port_range_min is a single port",
          usecase="translate_rule",
          model_input={"id": "r9", "sg": "sg1", "direction": "egress",
                       "protocol": "tcp", "min": 8080, "max": None},
          expect_value={"ports": "8080", "protocol": "tcp"}),

    # ==================== T3 backlog: A20 CLI ====================
    Frame("CLI-01.a", 3, "A20",
          "validate OK line carries the rule count",
          files={"groups/web.yaml": _group(members=()),
                 "rules/web.yaml": _rules(ingress=[("0.0.0.0/0", "tcp", '"22"')])},
          argv=["validate"], expect_rc=0,
          expect_out=("OK: 1 groups, 1 rules",)),
    Frame("CLI-12.a", 3, "A21",
          "apply --yes --json carries per-action results",
          **_cli(argv=["apply", "--yes", "--json"], expect_rc=0,
                 expect_out=('"results"',),
                 expect_json={"summary": {"add": 2, "change": 0, "destroy": 0}})),
    Frame("CLI-12.b", 3, "A21",
          "destroy --json renders the teardown plan",
          files={"groups/web.yaml": _group(members=())},
          cloud={"sgs": [{"id": "sg-1", "name": "web"}]},
          argv=["destroy", "web", "--json"], expect_rc=0,
          expect_json={"summary": {"add": 0, "change": 0, "destroy": 1}}),
    Frame("CLI-15", 3, "A19",
          "throttled --yes exits 1 with a resume hint",
          **_cli(argv=["apply", "--yes"],
                 cloud={"nics": [{"port_id": "p1", "ip": "10.0.1.10"}],
                        "budget": 1},
                 expect_rc=1, expect_out=("1 throttled", "re-run to resume"))),
    Frame("CLI-16", 3, "A20",
          "non-numeric SERVICE_CALL_BUDGET falls back to 25",
          model_call="load_config",
          env={"SERVICE_CALL_BUDGET": "not-a-number"},
          expect_value={"budget": 25}),
    Frame("CLI-16.a", 3, "A20", "numeric SERVICE_CALL_BUDGET is honored",
          model_call="load_config", env={"SERVICE_CALL_BUDGET": "40"},
          expect_value={"budget": 40}),
    Frame("CLI-16.b", 3, "A20", "budget 0 is a valid (pessimistic) value",
          model_call="load_config", env={"SERVICE_CALL_BUDGET": "0"},
          expect_value={"budget": 0}),
    Frame("CLI-16.c", 3, "A20", "SSL_VERIFY=false disables verification",
          model_call="load_config", env={"SSL_VERIFY": "false"},
          expect_value={"ssl_verify": False}),
    Frame("CLI-16.d", 3, "A20", "SSL_VERIFY unset verifies by default",
          model_call="load_config", env={"SSL_VERIFY": None},
          expect_value={"ssl_verify": True}),
    Frame("CLI-16.e", 3, "A20", "CA_BUNDLE feeds the config verbatim",
          model_call="load_config", env={"CA_BUNDLE": "/tmp/ca.pem"},
          expect_value={"ca_bundle": "/tmp/ca.pem"}),
    Frame("CLI-18", 3, "A20",
          "--project defaults to the working directory",
          **_cli(argv=["plan"], raw_argv=True, chdir=True, expect_rc=0,
                 expect_out=("+", "member"), expect_call_log=[])),
    Frame("CLI-19", 3, "A20",
          "nonexistent --project fails cleanly",
          files={"groups/web.yaml": _group()},
          argv=["plan", "--project", "no-such-project-dir"],
          raw_argv=True, expect_rc=1,
          expect_err=("no groups/ directory",)),

    # ============ T1 remainder (breadth over covered behaviour) ============
    Frame("NAME-01", 1, "A1", "typical hyphenated name is valid",
          model_call="parse_group",
          model_input={"name": "web-tier", "description": "web",
                       "members": [{"ip": "10.0.1.10"}, {"ip": "10.0.1.11"}]},
          expect_ok=True,
          expect_value=("web-tier", "web", ("10.0.1.10", "10.0.1.11"))),
    Frame("NAME-03", 1, "A1", "IP-lookalike name is rejected first",
          model_call="parse_group", model_input={"name": "10.0.1.10", "members": []},
          expect_ok=False, expect_error_contains=("must not look like an IP/CIDR",)),
    Frame("NAME-03.a", 1, "A1", "CIDR-lookalike name is rejected first",
          model_call="parse_group", model_input={"name": "10.0.0.0/8", "members": []},
          expect_ok=False, expect_error_contains=("must not look like an IP/CIDR",)),
    Frame("DESC-01", 1, "A2", "absent description defaults to empty",
          model_call="parse_group", model_input={"name": "web"},
          expect_ok=True, expect_value=("web", "", ())),
    Frame("DESC-01.a", 1, "A2", "empty-string description stays empty",
          model_call="parse_group", model_input={"name": "web", "description": ""},
          expect_ok=True, expect_value=("web", "", ())),
    Frame("DESC-02", 1, "A2", "non-string description is rejected",
          model_call="parse_group", model_input={"name": "web", "description": 5},
          expect_ok=False, expect_error_contains=("description must be a string",)),
    Frame("MEMB-01", 1, "A3", "absent members defaults to empty",
          model_call="parse_group", model_input={"name": "web"},
          expect_ok=True, expect_value=("web", "", ())),
    Frame("MEMB-01.a", 1, "A3", "empty members list is valid",
          model_call="parse_group", model_input={"name": "web", "members": []},
          expect_ok=True, expect_value=("web", "", ())),
    Frame("MEMB-02", 1, "A3", "non-list members is rejected",
          model_call="parse_group",
          model_input={"name": "web", "members": "10.0.1.10"},
          expect_ok=False, expect_error_contains=("members must be a list",)),
    Frame("MIP-01", 1, "A4", "mapping with a valid ip is the happy member",
          model_call="parse_group",
          model_input={"name": "g", "members": [{"ip": "10.0.1.10"}]},
          expect_ok=True, expect_value=("g", "", ("10.0.1.10",))),
    Frame("MIP-02", 1, "A4", "extra keys in a member entry are tolerated",
          model_call="parse_group",
          model_input={"name": "g",
                       "members": [{"ip": "10.0.1.10", "comment": "web-01"}]},
          expect_ok=True, expect_value=("g", "", ("10.0.1.10",))),
    Frame("MIP-03", 1, "A4", "bare-string member entry is rejected",
          model_call="parse_group", model_input={"name": "g", "members": ["10.0.1.10"]},
          expect_ok=False,
          expect_error_contains=("member must be a mapping with an 'ip' key",)),
    Frame("MIP-04", 1, "A4", "member mapping without ip is rejected",
          model_call="parse_group", model_input={"name": "g", "members": [{}]},
          expect_ok=False,
          expect_error_contains=("member must be a mapping with an 'ip' key",)),
    Frame("MIP-05", 1, "A4", "non-string ip is rejected",
          model_call="parse_group", model_input={"name": "g", "members": [{"ip": 10}]},
          expect_ok=False, expect_error_contains=("ip must be a string",)),
    Frame("MIP-05.a", 1, "A4", "out-of-range ip is rejected",
          model_call="parse_group",
          model_input={"name": "g", "members": [{"ip": "999.0.0.1"}]},
          expect_ok=False, expect_error_contains=("is not a valid address",)),
    Frame("MIP-05.b", 1, "A4", "leading-zero ip spelling is rejected",
          model_call="parse_group",
          model_input={"name": "g", "members": [{"ip": "010.0.1.10"}]},
          expect_ok=False, expect_error_contains=("is not a valid address",)),
    Frame("MIP-05.c", 1, "A4", "IPv6 member ip is not supported",
          model_call="parse_group", model_input={"name": "g", "members": [{"ip": "::1"}]},
          expect_ok=False, expect_error_contains=("IPv6",)),
    Frame("MIP-06", 1, "A4", "duplicate member ip (address-based) is rejected",
          model_call="parse_group",
          model_input={"name": "g",
                       "members": [{"ip": "10.0.1.10"}, {"ip": "10.0.1.10"}]},
          expect_ok=False, expect_error_contains=("duplicate ip",)),
    Frame("SGF-01", 1, "A5", "typical security_group is valid",
          model_call="parse_rules_file",
          model_input={"security_group": "app-tier", "ingress": [
              {"source": "web-tier", "protocol": "tcp", "ports": "8080"}]},
          expect_ok=True,
          expect_value={"sg": "app-tier", "ingress_managed": True,
                        "egress_managed": False, "ingress": 1, "egress": 0,
                        "rule0": ("ingress", "tcp", "8080", ("group", "web-tier"))}),
    Frame("SECT-01", 1, "A6", "present sections parse their rules",
          model_call="parse_rules_file",
          model_input={"security_group": "x", "ingress": [
              {"source": "a", "protocol": "tcp", "ports": "8080"},
              {"source": "0.0.0.0/0", "protocol": "icmp"}],
              "egress": [{"destination": "db", "protocol": "tcp",
                          "ports": [5432]}]},
          expect_ok=True,
          expect_value={"sg": "x", "ingress_managed": True,
                        "egress_managed": True, "ingress": 2, "egress": 1,
                        "rule0": ("ingress", "tcp", "8080", ("group", "a"))}),
    Frame("SECT-02", 1, "A6", "empty list means managed remove-all",
          model_call="parse_rules_file",
          model_input={"security_group": "x", "ingress": []},
          expect_ok=True,
          expect_value={"sg": "x", "ingress_managed": True,
                        "egress_managed": False, "ingress": 0, "egress": 0}),
    Frame("SECT-03", 1, "A6", "absent section means unmanaged",
          model_call="parse_rules_file", model_input={"security_group": "x"},
          expect_ok=True,
          expect_value={"sg": "x", "ingress_managed": False,
                        "egress_managed": False, "ingress": 0, "egress": 0}),
    Frame("SECT-04", 1, "A6", "ingress null is the remove-all guidance error",
          model_call="parse_rules_file",
          model_input={"security_group": "x", "ingress": None},
          expect_ok=False,
          expect_error_contains=("ingress must be a list", "remove-all")),
    Frame("REMOTE-01", 1, "A7", "plain name is a group remote",
          model_call="parse_remote", model_input="web-tier",
          expect_ok=True, expect_value=("group", "web-tier")),
    Frame("REMOTE-02", 1, "A7", "slash form is a CIDR remote",
          model_call="parse_remote", model_input="10.0.0.0/8",
          expect_ok=True, expect_value=("cidr", "10.0.0.0/8")),
    Frame("REMOTE-02.a", 1, "A7", "the any-remote CIDR is valid",
          model_call="parse_remote", model_input="0.0.0.0/0",
          expect_ok=True, expect_value=("cidr", "0.0.0.0/0")),
    Frame("REMOTE-03.a", 1, "A7", "bare ip normalises to /32",
          model_call="parse_remote", model_input="203.0.113.7",
          expect_ok=True, expect_value=("cidr", "203.0.113.7/32")),
    Frame("REMOTE-03.b", 1, "A7", "host bits are masked off",
          model_call="parse_remote", model_input="10.0.0.1/8",
          expect_ok=True, expect_value=("cidr", "10.0.0.0/8")),
    Frame("REMOTE-04", 1, "A7", "invalid prefix length raises",
          model_call="parse_remote", model_input="10.0.0.0/99",
          expect_ok=False, expect_error_contains=("10.0.0.0/99",)),
    Frame("REMOTE-05", 1, "A7", "IPv6 CIDR is rejected",
          model_call="parse_remote", model_input="2001:db8::/32",
          expect_ok=False, expect_error_contains=("IPv6",)),
    Frame("REMOTE-05.a", 1, "A7", "IPv6 bare address is rejected",
          model_call="parse_remote", model_input="::1",
          expect_ok=False, expect_error_contains=("IPv6",)),
    Frame("PROTO-01", 1, "A8", "tcp is a valid protocol",
          model_call="parse_rules_file",
          model_input={"security_group": "x", "ingress": [
              {"source": "10.0.0.0/8", "protocol": "tcp", "ports": "22"}]},
          expect_ok=True,
          expect_value={"sg": "x", "ingress_managed": True,
                        "egress_managed": False, "ingress": 1, "egress": 0,
                        "rule0": ("ingress", "tcp", "22", ("cidr", "10.0.0.0/8"))}),
    Frame("PROTO-02", 1, "A8", "unknown protocol is rejected with the list",
          model_call="parse_rules_file",
          model_input={"security_group": "x", "ingress": [
              {"source": "a", "protocol": "sctp"}]},
          expect_ok=False, expect_error_contains=("protocol must be one of",)),
    Frame("PROTO-02.a", 1, "A8", "absent protocol is rejected",
          model_call="parse_rules_file",
          model_input={"security_group": "x", "ingress": [{"source": "a"}]},
          expect_ok=False, expect_error_contains=("protocol must be one of",)),
    Frame("PORTS-01", 1, "A9", "single port as a string",
          model_call="parse_ports", model_input="80",
          expect_ok=True, expect_value="80"),
    Frame("PORTS-01.a", 1, "A9", "single port as an int",
          model_call="parse_ports", model_input=8080,
          expect_ok=True, expect_value="8080"),
    Frame("PORTS-01.b", 1, "A9", "mixed str/int list normalises",
          model_call="parse_ports", model_input=["22", 443],
          expect_ok=True, expect_value="22,443"),
    Frame("PORTS-02", 1, "A9", "a range stays a range",
          model_call="parse_ports", model_input="8000-9000",
          expect_ok=True, expect_value="8000-9000"),
    Frame("PORTS-02.a", 1, "A9", "mixed singles and ranges",
          model_call="parse_ports", model_input="80,443,8000-9000",
          expect_ok=True, expect_value="80,443,8000-9000"),
    Frame("PORTS-03", 1, "A9", "None means all ports",
          model_call="parse_ports", model_input=None,
          expect_ok=True, expect_value=None),
    Frame("PORTS-03.a", 1, "A9", "empty string means all ports",
          model_call="parse_ports", model_input="",
          expect_ok=True, expect_value=None),
    Frame("PORTS-03.b", 1, "A9", "empty list means all ports",
          model_call="parse_ports", model_input=[],
          expect_ok=True, expect_value=None),
    Frame("PORTS-04", 1, "A9", "unsorted input is sorted",
          model_call="parse_ports", model_input="443,80",
          expect_ok=True, expect_value="80,443"),
    Frame("PORTS-04.a", 1, "A9", "adjacent ports merge into a range",
          model_call="parse_ports", model_input="80,81,82",
          expect_ok=True, expect_value="80-82"),
    Frame("PORTS-04.b", 1, "A9", "adjacent ranges merge",
          model_call="parse_ports", model_input="80-81,82-83",
          expect_ok=True, expect_value="80-83"),
    Frame("PORTS-04.c", 1, "A9", "a gap keeps entries apart",
          model_call="parse_ports", model_input="80,82",
          expect_ok=True, expect_value="80,82"),
    Frame("PORTS-04.d", 1, "A9", "spaces around entries are tolerated",
          model_call="parse_ports", model_input="80, 443",
          expect_ok=True, expect_value="80,443"),
    Frame("PORTS-04.e", 1, "A9", "duplicate port collapses",
          model_call="parse_ports", model_input="80,80",
          expect_ok=True, expect_value="80"),
    Frame("PORTS-04.f", 1, "A9", "contained range is absorbed",
          model_call="parse_ports", model_input="1-100,50-60",
          expect_ok=True, expect_value="1-100"),
    Frame("PORTS-05", 1, "A9", "port 0 is out of bounds",
          model_call="parse_ports", model_input="0",
          expect_ok=False, expect_error_contains=("out of range",)),
    Frame("PORTS-05.a", 1, "A9", "port 65536 is out of bounds",
          model_call="parse_ports", model_input="65536",
          expect_ok=False, expect_error_contains=("out of range",)),
    Frame("PORTS-05.b", 1, "A9", "port 70000 is out of bounds",
          model_call="parse_ports", model_input="70000",
          expect_ok=False, expect_error_contains=("out of range",)),
    Frame("PORTS-05.c", 1, "A9", "reversed range is rejected",
          model_call="parse_ports", model_input="9000-8000",
          expect_ok=False, expect_error_contains=("reversed range",)),
    Frame("PORTS-07", 1, "A9",
          "21 merged entries hit the multiport cap",
          model_call="parse_ports",
          model_input=",".join(str(p) for p in range(1, 43, 2)),
          expect_ok=False, expect_error_contains=("at most 20",)),
    Frame("PORTS-07.a", 1, "A9", "20 adjacent ports merge to 1-20",
          model_call="parse_ports",
          model_input=",".join(str(p) for p in range(1, 21)),
          expect_ok=True, expect_value="1-20"),
    Frame("PORTS-08", 1, "A9", "the full range means all ports",
          model_call="parse_ports", model_input="1-65535",
          expect_ok=True, expect_value=None),
    Frame("PORTS-08.a", 1, "A9", "split full range still means all ports",
          model_call="parse_ports", model_input="1-100,101-65535",
          expect_ok=True, expect_value=None),
    Frame("PP-01", 1, "A10", "icmp with ports is rejected",
          model_call="parse_rules_file",
          model_input={"security_group": "x", "ingress": [
              {"source": "a", "protocol": "icmp", "ports": "80"}]},
          expect_ok=False, expect_error_contains=("icmp rules must not have ports",)),
    Frame("PP-02.a", 1, "A10", "all with ports is rejected",
          model_call="parse_rules_file",
          model_input={"security_group": "x", "ingress": [
              {"source": "a", "protocol": "all", "ports": "80"}]},
          expect_ok=False, expect_error_contains=("all rules must not have ports",)),
    Frame("DUPRULE-01", 1, "A11", "exact duplicate rule identity is rejected",
          model_call="parse_rules_file",
          model_input={"security_group": "x", "ingress": [
              {"source": "d", "protocol": "tcp", "ports": "80"},
              {"source": "d", "protocol": "tcp", "ports": "80"}]},
          expect_ok=False, expect_error_contains=("duplicate",)),
    Frame("ACT-01", 1, "A19", "summary counts signs across payload kinds",
          model_call="actionlist_summary",
          model_input={"actions": [
              ("+", "member", "web", "ip 1.2.3.4", "abc", ("AttachNic", "sg", "abc")),
              ("-", "rule", "web", "old rule", "r1", None),
              ("~", "group", "web", "description", "sg1", None),
              ("+", "group", "new", "new group", None, ("CreateSg", "d"))]},
          expect_value={"add": 2, "change": 1, "destroy": 1}),
    Frame("ACT-02", 1, "A19", "empty ActionList summarizes to zeros",
          model_call="actionlist_summary", model_input={"actions": []},
          expect_value={"add": 0, "change": 0, "destroy": 0}),
    Frame("MODEL-01", 1, "A19", "DesiredState is a plain container",
          model_call="desired_state", model_input={"groups": ["a"], "rules": ["a"]},
          expect_ok=True),

    # ============ T2 remainder (breadth over covered behaviour) ============
    Frame("STORE-01", 2, "A12", "happy path loads both directories",
          usecase="load",
          files={"groups/web-tier.yaml": _group(name="web-tier"),
                 "rules/web-tier.yaml": _rules(
                     sg="web-tier", ingress=[("bastion", "tcp", '"22"')])},
          expect_ok=True,
          expect_value={"groups": ["web-tier"], "rules": ["web-tier"]}),
    Frame("STORE-03", 2, "A12", "empty file is a load error",
          usecase="load", files={"groups/x.yaml": ""},
          expect_ok=False, expect_error_contains=("empty",)),
    Frame("STORE-03.c", 2, "A12", "scalar document is not a mapping",
          usecase="load", files={"groups/x.yaml": "hello\n"},
          expect_ok=False, expect_error_contains=("must be a YAML mapping",)),
    Frame("STORE-04", 2, "A12", "syntax errors carry the parser's line",
          usecase="load", files={"groups/bad.yaml": "name: bad\n  members: [\n"},
          expect_ok=False,
          expect_error_contains=("YAML syntax error", "line 2")),
    Frame("STORE-05", 2, "A12", "binary bytes are a read error",
          usecase="load", files={"groups/x.yaml": b"\xff\xfe\x00garbage"},
          expect_ok=False, expect_error_contains=("cannot read file",)),
    Frame("STORE-06", 2, "A12", ".yml sibling in groups/ warns",
          usecase="load",
          files={"groups/web.yaml": _group(members=()),
                 "groups/extra.yml": "name: extra\nmembers: []\n"},
          expect_ok=True, expect_warn=("groups/extra.yml",)),
    Frame("STORE-07", 2, "A12", "group stem must equal the declared name",
          usecase="load", files={"groups/oops.yaml": _group(name="web-tier", members=())},
          expect_ok=False, expect_error_contains=("filename must equal group name",)),
    Frame("STORE-08", 2, "A12", "rules stem must equal security_group",
          usecase="load",
          files={"groups/web.yaml": _group(members=()),
                 "rules/oops.yaml": _rules(sg="web", ingress=[])},
          expect_ok=False,
          expect_error_contains=("filename must equal security_group",)),
    Frame("STORE-09", 2, "A12", "two files declaring one group name",
          usecase="load",
          files={"groups/a.yaml": _group(name="dup", members=()),
                 "groups/b.yaml": _group(name="dup", members=())},
          expect_ok=False, expect_error_contains=("duplicate group name",)),
    Frame("STORE-10", 2, "A12", "two rules files for one security_group",
          usecase="load",
          files={"groups/web.yaml": _group(members=()),
                 "rules/web.yaml": _rules(sg="web", ingress=[]),
                 "rules/copy.yaml": _rules(sg="web", ingress=[])},
          expect_ok=False, expect_error_contains=("duplicate rules file",)),
    Frame("STORE-10.a", 2, "A12", "dangling rules file (no group file)",
          usecase="load",
          files={"groups/web.yaml": _group(members=()),
                 "rules/ghost.yaml": _rules(sg="ghost", ingress=[])},
          expect_ok=False, expect_error_contains=("has no groups/ghost.yaml",)),
    Frame("XVAL-01", 2, "A13", "valid cross-file references pass",
          usecase="validate",
          files={"groups/web.yaml": _group(members=()),
                 "groups/db.yaml": _group(name="db", members=()),
                 "rules/db.yaml": _rules(sg="db", ingress=[("web", "tcp", '"5432"')])},
          expect_ok=True),
    Frame("XVAL-02", 2, "A13", "remote group reference must exist",
          usecase="validate",
          files={"groups/web.yaml": _group(members=()),
                 "rules/web.yaml": _rules(sg="web", ingress=[("ghost", "tcp", '"80"')])},
          expect_ok=False, expect_error_contains=("unknown group 'ghost'",)),
    Frame("XVAL-03", 2, "A13", "orphan rules file is reported",
          usecase="validate",
          files={"groups/web.yaml": _group(members=()),
                 "rules/ghost.yaml": _rules(sg="ghost", ingress=[])},
          expect_ok=False, expect_error_contains=("has no groups/ghost.yaml",)),
    Frame("RES-01", 2, "A14", "exactly one NIC resolves the member",
          usecase="resolve", files={"groups/web.yaml": _group()},
          cloud={"nics": [{"port_id": "p1", "ip": "10.0.1.10", "vm": "web-01"}]},
          expect_ok=True, expect_nics=(("10.0.1.10", "p1"),)),
    Frame("RES-02", 2, "A14", "zero NIC matches is an error",
          usecase="resolve", files={"groups/web.yaml": _group()},
          cloud={}, expect_ok=False, expect_error_contains=("no NIC",)),
    Frame("RES-03", 2, "A14", "multiple NIC matches list their candidates",
          usecase="resolve", files={"groups/web.yaml": _group()},
          cloud={"nics": [{"port_id": "p1", "ip": "10.0.1.10"},
                          {"port_id": "p2", "ip": "10.0.1.10"}]},
          expect_ok=False, expect_error_contains=("matches multiple NICs",)),
    Frame("RES-04", 2, "A14", "overlap across groups is info, not error",
          usecase="resolve",
          files={"groups/web.yaml": _group(),
                 "groups/mon.yaml": _group(name="mon")},
          cloud={"nics": [{"port_id": "p1", "ip": "10.0.1.10"}]},
          expect_ok=True,
          expect_overlaps=("10.0.1.10 in groups mon, web",)),
    Frame("RES-05", 2, "A14", "mixed success and failure reports both",
          usecase="resolve",
          files={"groups/web.yaml": _group(),
                 "groups/db.yaml": _group(name="db", members=("10.0.9.99",))},
          cloud={"nics": [{"port_id": "p1", "ip": "10.0.1.10"}]},
          expect_ok=False, expect_error_contains=("10.0.9.99",),
          expect_nics=(("10.0.1.10", "p1"),)),
    Frame("RATE-01", 2, "A22", "budget allows N then blocks",
          usecase="ratelimit",
          model_input={"budget": 3, "window": 300,
                       "ops": [("acquire",), ("acquire",), ("acquire",),
                               ("acquire",)]},
          expect_value=[True, True, True, False]),
    Frame("RATE-02", 2, "A22", "window rollover resets the budget",
          usecase="ratelimit",
          model_input={"budget": 1, "window": 300,
                       "ops": [("acquire",), ("acquire",),
                               ("advance", 301), ("acquire",)]},
          expect_value=[True, False, True]),
    Frame("RATE-03", 2, "A22", "external throttle halves the limit",
          usecase="ratelimit",
          model_input={"budget": 10, "window": 300,
                       "ops": [("acquire",), ("throttle",),
                               ("acquire",), ("acquire",), ("acquire",),
                               ("acquire",), ("acquire",)]},
          expect_value=[True, True, True, True, True, False]),
    Frame("RATE-03.a", 2, "A22",
          "external throttle late in the window pins the limit to used",
          usecase="ratelimit",
          model_input={"budget": 10, "window": 300,
                       "ops": [("acquire",), ("acquire",), ("acquire",),
                               ("acquire",), ("acquire",), ("acquire",),
                               ("acquire",), ("throttle",), ("acquire",)]},
          expect_value=[True, True, True, True, True, True, True, False]),
    Frame("XLATE-02", 2, "A23", "wire min/max translate to a port range",
          usecase="translate_rule",
          model_input={"id": "r1", "sg": "sg1", "direction": "ingress",
                       "protocol": "tcp", "min": 80, "max": 81,
                       "prefix": "10.0.0.0/8"},
          expect_value={"ports": "80-81", "protocol": "tcp",
                        "remote_ip_prefix": "10.0.0.0/8"}),
    Frame("XLATE-02.a", 2, "A23",
          "all-protocol wire rule: protocol and ports both None",
          usecase="translate_rule",
          model_input={"id": "r2", "sg": "sg1", "direction": "egress",
                       "protocol": None, "min": None, "max": None,
                       "rgid": "sg9"},
          expect_value={"ports": None, "protocol": None,
                        "remote_group_id": "sg9"}),
    Frame("XLATE-02.b", 2, "A23",
          "icmp type/code on the wire is never ports",
          usecase="translate_rule",
          model_input={"id": "r3", "sg": "sg1", "direction": "ingress",
                       "protocol": "icmp", "min": 8, "max": 0,
                       "prefix": "10.0.113.0/24"},
          expect_value={"ports": None, "protocol": "icmp"}),
    Frame("FAKE-01", 2, "A24", "writer round-trip: create, update, delete",
          usecase="fake",
          model_input=(("create_sg", "web", "d"),
                       ("update_sg", "id-0001", "d2"),
                       ("delete_sg", "id-0001")),
          expect_call_log=["create_sg:web", "update_sg:id-0001",
                           "delete_sg:id-0001"],
          expect_cloud=(("sg_missing", "web"),)),
    Frame("FAKE-01.a", 2, "A24", "description update is observable",
          usecase="fake",
          model_input=(("create_sg", "web", "d"), ("update_sg", "id-0001", "d2")),
          expect_cloud=(("sg_exists", "web"), ("sg_desc", "web", "d2"))),
    Frame("FAKE-02", 2, "A24",
          "create_rule resolves the remote group NAME to its id",
          usecase="fake",
          model_input=(("create_sg", "first", ""), ("create_sg", "second", ""),
                       ("create_rule", "id-0002", "ingress", "tcp", "443",
                        ("group", "first"))),
          expect_cloud=(("rule_match", "id-0002",
                         {"remote_group_id": "id-0001", "ports": "443"}),)),
    Frame("PLAN-01", 2, "A15",
          "new group: sg create first, then member, then rules",
          usecase="plan",
          files={"groups/fresh.yaml": _group(name="fresh"),
                 "rules/fresh.yaml": _rules(
                     sg="fresh",
                     ingress=[("203.0.113.0/24", "tcp", '"22"')],
                     egress=[("0.0.0.0/0", "tcp", '"443"')])},
          cloud={"nics": [{"port_id": "p1", "ip": "10.0.1.10"}]},
          expect_actions=(("+", "group", "fresh"), ("+", "member", "fresh"),
                          ("+", "rule", "fresh"), ("+", "rule", "fresh")),
          expect_unmanaged=()),
    Frame("PLAN-02", 2, "A15", "description drift is a change action",
          usecase="plan",
          files={"groups/web.yaml": _group(desc="new desc")},
          cloud={"sgs": [{"id": "sg-web", "name": "web", "description": "old"}],
                 "nics": [{"port_id": "p1", "ip": "10.0.1.10"}],
                 "attached": [["sg-web", "p1"]]},
          expect_actions=(("~", "group", "web"),), expect_unmanaged=()),
    Frame("PLAN-03", 2, "A15", "cloud SG without code is inventoried, kept",
          usecase="plan", files={"groups/.keep": ""},
          cloud={"sgs": [{"id": "sg-x", "name": "extra"}]},
          expect_actions=(),
          expect_unmanaged=("security group 'extra' (no groups/extra.yaml)",)),
    Frame("PLAN-04", 2, "A17",
          "no rules file: both directions unmanaged, with counts",
          usecase="plan", files={"groups/y.yaml": _group(name="y", members=())},
          cloud={"sgs": [{"id": "sg-y", "name": "y"}],
                 "rules": [
                     {"id": "ry1", "sg": "sg-y", "direction": "ingress",
                      "protocol": "tcp", "ports": "80", "prefix": "0.0.0.0/0"},
                     {"id": "ry2", "sg": "sg-y", "direction": "egress",
                      "protocol": "tcp", "ports": "443", "prefix": "0.0.0.0/0"}]},
          expect_actions=(),
          expect_unmanaged=("ingress rules of y (1 cloud rules untouched)",
                            "egress rules of y (1 cloud rules untouched)")),
    Frame("PLAN-05", 2, "A16",
          "identity: cloud all-protocol + unset remote equals code all/any",
          usecase="plan",
          files={"groups/eq.yaml": _group(name="eq", members=()),
                 "rules/eq.yaml": _rules(sg="eq", egress=[("0.0.0.0/0", "all", None)])},
          cloud={"sgs": [{"id": "sg-eq", "name": "eq"}],
                 "rules": [{"id": "eq1", "sg": "sg-eq", "direction": "egress",
                            "protocol": None, "ports": None,
                            "rgid": None, "prefix": None}]},
          expect_actions=(), expect_unmanaged=()),
    Frame("PLAN-07", 2, "A16", "identity: non-canonical cloud CIDR converges",
          usecase="plan",
          files={"groups/nc.yaml": _group(name="nc", members=()),
                 "rules/nc.yaml": _rules(
                     sg="nc", ingress=[("10.0.0.0/8", "tcp", '"80"')])},
          cloud={"sgs": [{"id": "sg-nc", "name": "nc"}],
                 "rules": [{"id": "nc1", "sg": "sg-nc", "direction": "ingress",
                            "protocol": "tcp", "ports": "80",
                            "prefix": "10.0.0.1/8"}]},
          expect_actions=(), expect_unmanaged=()),
    Frame("PLAN-09", 2, "A16",
          "changed rule is an honest minus/plus pair (no update op)",
          usecase="plan",
          files={"groups/web.yaml": _group(members=()),
                 "rules/web.yaml": _rules(sg="web", ingress=[("web", "tcp", '"8080"')])},
          cloud={"sgs": [{"id": "sg-web", "name": "web"}],
                 "rules": [{"id": "r1", "sg": "sg-web", "direction": "ingress",
                            "protocol": "tcp", "ports": "8080",
                            "prefix": "0.0.0.0/0"}]},
          expect_actions=(("+", "rule", "web", "from group:web"),
                          ("-", "rule", "web", "from cidr:0.0.0.0/0")),
          expect_unmanaged=()),
    Frame("PLAN-10", 2, "A16",
          "multi-port code rule converges against split cloud rules",
          usecase="plan",
          files={"groups/m.yaml": _group(name="m", members=()),
                 "rules/m.yaml": _rules(
                     sg="m", ingress=[("10.0.0.0/8", "tcp", '"22,443"')])},
          cloud={"sgs": [{"id": "sg-m", "name": "m"}],
                 "rules": [
                     {"id": "m1", "sg": "sg-m", "direction": "ingress",
                      "protocol": "tcp", "ports": "22", "prefix": "10.0.0.0/8"},
                     {"id": "m2", "sg": "sg-m", "direction": "ingress",
                      "protocol": "tcp", "ports": "443", "prefix": "10.0.0.0/8"}]},
          expect_actions=(), expect_unmanaged=()),
    Frame("PLAN-11", 2, "A16",
          "partial multi-port cloud creates only the missing subrange",
          usecase="plan",
          files={"groups/m.yaml": _group(name="m", members=()),
                 "rules/m.yaml": _rules(
                     sg="m", ingress=[("10.0.0.0/8", "tcp", '"22,443"')])},
          cloud={"sgs": [{"id": "sg-m", "name": "m"}],
                 "rules": [{"id": "m1", "sg": "sg-m", "direction": "ingress",
                            "protocol": "tcp", "ports": "22",
                            "prefix": "10.0.0.0/8"}]},
          expect_actions=(("+", "rule", "m", " 443 "),), expect_unmanaged=()),
    Frame("PLAN-12", 2, "A16",
          "overlapping code rules create each subrange exactly once",
          usecase="plan",
          files={"groups/x.yaml": _group(name="x", members=()),
                 "rules/x.yaml": _rules(sg="x", ingress=[
                     ("0.0.0.0/0", "tcp", '"22,443"'),
                     ("0.0.0.0/0", "tcp", '"443,8080"')])},
          cloud={"sgs": [{"id": "sg-x", "name": "x"}]},
          expect_actions=(("+", "rule", "x", " 22 "),
                          ("+", "rule", "x", " 443 "),
                          ("+", "rule", "x", " 8080 ")),
          expect_unmanaged=()),
    Frame("PLAN-13", 2, "A16",
          "unrepresentable cloud remote is an honest delete",
          usecase="plan",
          files={"groups/v6.yaml": _group(name="v6", members=()),
                 "rules/v6.yaml": _rules(sg="v6", empty=("egress",))},
          cloud={"sgs": [{"id": "sg-v6", "name": "v6"}],
                 "rules": [{"id": "v1", "sg": "sg-v6", "direction": "egress",
                            "protocol": None, "ports": None,
                            "prefix": "::/0"}]},
          expect_actions=(("-", "rule", "v6"),),
          expect_clears=("egress rules of v6",), expect_unmanaged=()),
    Frame("PLAN-16", 2, "A15",
          "duplicate cloud SG names abort planning with every id listed",
          usecase="plan", files={"groups/web.yaml": _group(members=())},
          cloud={"sgs": [{"id": "sg-a", "name": "web", "description": "d1"},
                         {"id": "sg-b", "name": "web", "description": "d2"}]},
          expect_ok=False,
          expect_error_contains=("duplicate cloud security group name",
                                 "'web' (sg-a, sg-b)")),
    Frame("PLAN-17", 2, "A17",
          "managed-empty direction with no cloud rules raises no alarm",
          usecase="plan",
          files={"groups/web.yaml": _group(members=()),
                 "rules/web.yaml": _rules(sg="web", empty=("ingress", "egress"))},
          cloud={"sgs": [{"id": "sg-web", "name": "web"}]},
          expect_actions=(), expect_clears=(), expect_unmanaged=()),
    Frame("DSTR-01", 2, "A15",
          "destroy detaches every member then deletes the SG",
          usecase="destroy", model_input="x",
          files={"groups/x.yaml": _group(name="x", members=())},
          cloud={"sgs": [{"id": "sg-x", "name": "x"}],
                 "nics": [{"port_id": "px1", "ip": "10.9.9.1"},
                          {"port_id": "px2", "ip": "10.9.9.2"}],
                 "attached": [["sg-x", "px1"], ["sg-x", "px2"]]},
          expect_actions=(("-", "member", "x"), ("-", "member", "x"),
                          ("-", "group", "x")),
          expect_call_log=["detach:px1->sg-x", "detach:px2->sg-x",
                           "delete_sg:sg-x"],
          expect_cloud=(("sg_missing", "x"),)),
    Frame("EXEC-01", 2, "A19",
          "rank order creates referenced groups before remote rules",
          usecase="execute",
          files={"groups/a.yaml": _group(name="a", members=()),
                 "groups/b.yaml": _group(name="b", members=()),
                 "rules/a.yaml": _rules(sg="a", ingress=[("b", "tcp", '"22"')])},
          expect_results=("ok", "ok", "ok"),
          expect_call_log=["create_sg:a", "create_sg:b", "create_rule:id-0001"],
          expect_cloud=(("sg_count", 2),
                        ("rule_match", "sg-of:a",
                         {"ports": "22", "remote_group_id": "id-0002"}))),
    Frame("EXEC-02", 2, "A19",
          "empty sg_id payloads substitute the just-created id",
          usecase="execute", files={"groups/web.yaml": _group()},
          cloud={"nics": [{"port_id": "p1", "ip": "10.0.1.10"}]},
          expect_results=("ok", "ok"), expect_audit=("web",),
          expect_cloud=(("sg_exists", "web"), ("attached", "sg-of:web", "p1"))),
    Frame("EXEC-04", 2, "A19", "budget 1 throttles the second write",
          usecase="execute", files={"groups/web.yaml": _group()},
          cloud={"nics": [{"port_id": "p1", "ip": "10.0.1.10"}], "budget": 1},
          expect_results=("ok", "throttled"),
          expect_cloud=(("sg_exists", "web"), ("detached", "sg-of:web", "p1"))),
    Frame("EXEC-06", 2, "A19",
          "throttle then resume completes exactly the remainder",
          usecase="execute_resume",
          model_input={"phases": [{"budget": 3}, {"budget": None}]},
          files={"groups/alpha.yaml": _group(name="alpha"),
                 "groups/beta.yaml": _group(name="beta", members=()),
                 "rules/alpha.yaml": _rules(
                     sg="alpha", ingress=[("203.0.113.0/24", "tcp", '"22"')]),
                 "rules/beta.yaml": _rules(
                     sg="beta", ingress=[("203.0.113.0/24", "tcp", '"443"')])},
          cloud={"nics": [{"port_id": "p1", "ip": "10.0.1.10"}]},
          expect_phases=(("ok", "ok", "ok", "throttled", "throttled"),
                         ("ok", "ok"))),
    Frame("REND-01", 2, "A21",
          "table: prefixed ids, footer, unmanaged, overlap, dry run",
          usecase="render_plan",
          model_input={"quota": {"needed": 7, "left": 18}},
          files={"groups/mon.yaml": _group(name="mon"),
                 "groups/web.yaml": _group(desc="b"),
                 "rules/web.yaml": _rules(
                     sg="web", ingress=[("10.0.0.0/8", "tcp", '"22"')])},
          cloud={"sgs": [{"id": "sg-web", "name": "web", "description": "a"},
                         {"id": "sg-extra", "name": "extra"}],
                 "rules": [{"id": "r1", "sg": "sg-web", "direction": "ingress",
                            "protocol": "tcp", "ports": "8080",
                            "prefix": "0.0.0.0/0"}],
                 "nics": [{"port_id": "p1", "ip": "10.0.1.10"},
                          {"port_id": "p2", "ip": "10.0.1.99"}],
                 "attached": [["sg-web", "p2"]]},
          expect_out=("nic=p1", "sg=sg-web", "rule=r1", "(new)",
                      "Plan: 4 to add, 1 to change, 2 to destroy.",
                      "NOT MANAGED: security group 'extra'",
                      "INFO: IP overlap (allowed): 10.0.1.10 in groups mon, web.",
                      "Quota: 7 calls needed, 18 left in this window.",
                      "Dry run")),
    Frame("REND-02", 2, "A21",
          "apply mode appends the RESULT column and completion footer",
          usecase="render_exec",
          model_input={"quota": {"needed": 2, "left": 23}},
          files={"groups/web.yaml": _group()},
          cloud={"nics": [{"port_id": "p1", "ip": "10.0.1.10"}]},
          expect_out=("RESULT", "ok",
                      "Apply complete: 2 ok, 0 failed, 0 throttled"),
          expect_out_absent=("Dry run",)),
    Frame("REND-03", 2, "A21", "json shape: actions, summary, quota, info",
          usecase="render_json",
          files={"groups/web.yaml": _group()},
          cloud={"nics": [{"port_id": "p1", "ip": "10.0.1.10"}]},
          expect_json={"summary": {"add": 2, "change": 0, "destroy": 0},
                       "quota": None, "unmanaged": [], "overlap": []}),

    # ============ T3 remainder (breadth over covered behaviour) ============
    Frame("CLI-01", 3, "A20", "validate ok, no gateway touched",
          files={"groups/web.yaml": _group(members=())},
          argv=["validate"], expect_rc=0,
          expect_out=("OK: 1 groups, 0 rules", "validation passed"),
          expect_call_log=[]),
    Frame("CLI-02", 3, "A20", "validate reports file errors on stderr",
          files={"groups/web.yaml": "name: web\nmembers:\n  - ip: 999.0.0.1\n"},
          argv=["validate"], expect_rc=1, expect_err=("999.0.0.1",)),
    Frame("CLI-03", 3, "A20", "plan is read-only",
          **_cli(argv=["plan"], expect_rc=0,
                 expect_out=("+", "member", "Dry run"), expect_call_log=[])),
    Frame("CLI-04", 3, "A20", "apply defaults to dry run",
          **_cli(argv=["apply"], expect_rc=0,
                 expect_out=("Dry run",), expect_call_log=[])),
    Frame("CLI-06", 3, "A20", "apply --yes performs the writes",
          **_cli(argv=["apply", "--yes"], expect_rc=0,
                 expect_out=("Apply complete: 2 ok",),
                 expect_cloud=(("sg_exists", "web"),
                               ("attached", "sg-of:web", "p1")))),
    Frame("CLI-06.a", 3, "A22",
          "post-write quota reflects already-spent writes",
          # no absent-pin: the pre-write preview legitimately shows the
          # pre-execute "25 left"; "23 left" present pins the FINAL table
          **_cli(argv=["apply", "--yes"], expect_rc=0,
                 expect_out=("23 left", "RESULT"))),
    Frame("CLI-10", 3, "A17",
          "clear-all warning names group and direction when stripping",
          files={"groups/web.yaml": _group(),
                 "rules/web.yaml": _rules(sg="web", empty=("egress",))},
          cloud={"sgs": [{"id": "sg-web", "name": "web"}],
                 "nics": [{"port_id": "p1", "ip": "10.0.1.10"}],
                 "attached": [["sg-web", "p1"]],
                 "rules": [{"id": "r1", "sg": "sg-web", "direction": "egress",
                            "protocol": "tcp", "ports": "80",
                            "prefix": "0.0.0.0/0"}]},
          argv=["apply", "--yes"], expect_rc=0,
          expect_out=("removes ALL egress rules of web",)),
    Frame("CLI-10.a", 3, "A17",
          "no clear-all warning when the direction strips nothing",
          files={"groups/web.yaml": _group(),
                 "rules/web.yaml": _rules(sg="web", empty=("egress",))},
          cloud={"sgs": [{"id": "sg-web", "name": "web"}],
                 "nics": [{"port_id": "p1", "ip": "10.0.1.10"}],
                 "attached": [["sg-web", "p1"]]},
          argv=["apply", "--yes"], expect_rc=0,
          expect_out_absent=("removes ALL",)),
    Frame("CLI-11", 3, "A20",
          "missing credentials name all four required vars",
          files={"groups/web.yaml": _group(members=())},
          argv=["plan"], inject_gateway=False, expect_rc=1,
          env={"HCS_AK": None, "HCS_SK": None, "HCS_PROJECT_ID": None,
               "HCS_ENDPOINT": None},
          expect_err=("HCS_AK", "HCS_SK", "HCS_PROJECT_ID", "HCS_ENDPOINT")),
    Frame("CLI-12", 3, "A21", "plan --json carries the summary",
          **_cli(argv=["plan", "--json"], expect_rc=0,
                 expect_json={"summary": {"add": 2, "change": 0,
                                          "destroy": 0}})),
    Frame("CLI-13", 3, "A20", "destroy --yes executes the teardown",
          files={"groups/web.yaml": _group(members=())},
          cloud={"sgs": [{"id": "sg-1", "name": "web"}]},
          argv=["destroy", "web", "--yes"], expect_rc=0,
          expect_cloud=(("sg_missing", "web"),)),
    Frame("CLI-13.a", 3, "A20", "destroy without --yes is a dry run",
          files={"groups/web.yaml": _group(members=())},
          cloud={"sgs": [{"id": "sg-1", "name": "web"}]},
          argv=["destroy", "web"], expect_rc=0,
          expect_out=("Dry run",), expect_call_log=[]),
    Frame("CLI-14.a", 3, "A20", "destroy of an unknown name fails cleanly",
          files={"groups/web.yaml": _group(members=())},
          argv=["destroy", "ghost"], expect_rc=1,
          expect_err=("no cloud security group named 'ghost'",)),
    Frame("CLI-17", 3, "A20", "--yes writes audit.jsonl in the project",
          **_cli(argv=["apply", "--yes"], expect_rc=0,
                 expect_files=("audit.jsonl",))),
    Frame("CLI-20", 3, "A15", "duplicate cloud names fail with a clean error",
          files={"groups/web.yaml": _group(members=())},
          cloud={"sgs": [{"id": "sg-a", "name": "web"},
                         {"id": "sg-b", "name": "web"}]},
          argv=["plan"], expect_rc=1,
          expect_err=("duplicate cloud security group name",)),
    Frame("CLI-21", 3, "A20",
          "--verbose plan streams progress to stderr, stdout unchanged",
          **_cli(argv=["plan", "--verbose"], expect_rc=0,
                 expect_out=("+", "member", "Dry run"),
                 expect_out_absent=("hcs-sg:",),
                 expect_err=("hcs-sg:", "gateway call",
                             "reading cloud snapshot"))),
    Frame("CLI-21.a", 3, "A20",
          "--verbose apply logs each action as it executes",
          **_cli(argv=["apply", "--yes", "--verbose"],
                 expect_rc=0,
                 expect_err=("hcs-sg:", "executing + group web",
                             "action ok: + group web"))),
    Frame("CLI-22", 3, "A20",
          "plan --yes is rejected at parse time with guidance",
          files={"groups/web.yaml": _group(members=())},
          argv=["plan", "--yes"], raw_argv=True,
          inject_gateway=False, expect_rc=2,
          expect_err=("read-only", "apply --yes")),
    Frame("CLI-23", 3, "A20",
          "--yes previews the plan table before writing it out",
          **_cli(argv=["apply", "--yes"], expect_rc=0,
                 expect_out=("Plan: 2 to add", "RESULT", "Apply complete"),
                 expect_cloud=(("sg_exists", "web"),))),
]

TIER1 = [f for f in FRAMES if f.tier == 1]
TIER2 = [f for f in FRAMES if f.tier == 2]
TIER3 = [f for f in FRAMES if f.tier == 3]

# Frames not expressible as deterministic rows; the hand-written depth
# tests remain their home. The coverage guard enforces a reason string.
DEFERRED: dict = {
    "XLATE-01": (
        "dispatch-table meta check (method existence AND request-class "
        "pairing) is reflection over the SDK surface, not a behavioural "
        "frame; pinned by test_dispatch_table_* in "
        "tests/adapters/test_huawei_translate.py"),
    "XLATE-03": (
        "chokepoint semantics (429 -> CloudThrottled + halved limit, "
        "budget short-circuit before the SDK, other errors -> CloudError) "
        "need a stub SDK client plus frozen limiter harness; stays "
        "hand-written in test_huawei_chokepoint_*"),
    "XLATE-04": (
        "remote-id cache refresh needs a stateful stub whose listing "
        "mutates the cache; pinned by "
        "test_name_to_uuid_resolution_uses_listing"),
    "XLATE-05": (
        "find_nics_by_ip filtering semantics (fixed_ips filter, id "
        "unused, dns_assignment vm names) need a stub ports client; "
        "stays hand-written"),
    "XLATE-06": (
        "marker pagination needs page-scripted stub clients (full page "
        "advances the marker, short page ends the loop) for three "
        "endpoints; stays hand-written"),
}

# Tier 4 stays hand-written under the cloud_contract marker
# (tests/contract/test_gateway_contract.py); ids map to dedicated tests.
TIER4: dict = {
    "CTRCT-01": "full protocol exercise, fake always + real gated",
    "CTRCT-02": "extended protocol round-trip: udp, icmp type/code, all",
}
